---
- name: Boot with CDROM
  command: virsh attach-disk 
    --domain {{ vm_name }}
    --source {{ install_cd }}
    --target vdd 
    --targetbus sata 
    --driver qemu 
    --type cdrom 
    --config 
    --sourcetype file  
    --subdriver raw 
    --mode readonly
  changed_when: True
  notify: Start VM with CDROM
- name: Start VM with CDROM
  virt:
    name: "{{ vm_name }}"
    state: running
  changed_when: True
  notify: Wait for VM boot with CDROM
- name: Wait for VM boot with CDROM
  local_action:
    module: wait_for
    port: 22
    host: "{{ provisioned_hostname }}"
    search_regex: OpenSSH
    delay: 3
    timeout: 60
    connect_timeout: 3 
  changed_when: True
  notify: Detach CDROM from booted VM
- name: Detach CDROM from booted VM
  command: virsh detach-disk --domain {{ vm_name }} --target vdd --config
