---
- name: Restart VM
  debug: msg="Restarting {{ vm_name }}"
  changed_when: true
  notify:
    - Stop VM
    - Remove CDROM before adding
    - Remove Windows Drivers CDROM before boot
    - Add CDROM
    - Start VM
    - Remove CDROM
    - Wait for VM boot 

- name: Check VM defined
  virt: command=get_vm name={{ vm_name }}
  register: vm_defined
  failed_when: false

- name: Check VM running
  virt: command=get_vm name={{ vm_name }}
  failed_when: false
  when: vm_defined.failed

- name: Stop VM
  virt: name={{ vm_name }} state=shutdown force=true

# removes from definition, but --config doesn't affect runtime
- name: Remove CDROM before adding
  command: virsh detach-disk --domain {{ vm_name }} --target vdd --config
  failed_when: false
  when: cdrom_install|bool

# removes from definition, but --config doesn't affect runtime
- name: Remove Windows Drivers CDROM before boot
  command: virsh detach-disk --domain {{ vm_name }} --target vde --config
  failed_when: false
  when: cdrom_install|bool or qemu_windows_drivers|bool

- name: Add Windows Drivers CDROM
  command: virsh attach-disk 
    --domain {{ vm_name }}
    --source {{ windows_drivers_cd_path }}
    --target vde 
    --targetbus sata 
    --driver qemu 
    --type cdrom 
    --config 
    --sourcetype file  
    --subdriver raw 
    --mode readonly
  when: cdrom_install|bool or qemu_windows_drivers|bool

- name: Add CDROM
  command: virsh attach-disk 
    --domain {{ vm_name }}
    --source {{ install_cd_path }}
    --target vdd 
    --targetbus sata 
    --driver qemu 
    --type cdrom 
    --config 
    --sourcetype file  
    --subdriver raw 
    --mode readonly
  when: cdrom_install|bool

- name: Start VM
  virt:
    name: "{{ vm_name }}"
    state: running
  when: vm_start|bool

# removes from definition, but --config doesn't affect runtime
- name: Remove CDROM
  command: virsh detach-disk --domain {{ vm_name }} --target vdd --config
  when: cdrom_install|bool

# removes from definition, but --config doesn't affect runtime
- name: Remove Windows Drivers CDROM
  command: virsh detach-disk --domain {{ vm_name }} --target vde --config
  when: cdrom_install|bool or qemu_windows_drivers|bool

- name: Wait for VM boot
  local_action:
    module: wait_for
    port: 22
    host: "{{ provisioned_hostname }}"
    search_regex: OpenSSH
    delay: 3
    timeout: 60
    connect_timeout: 3 
  when: vm_linux|bool

